#!/usr/bin/env bash
pip install --upgrade pip
if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX, need to specify the CFLAGS for fairseq https://github.com/pytorch/fairseq
    echo "Mac OS"
    CFLAGS="-stdlib=libc++" pip install -e . --upgrade --no-cache-dir --progress-bar off --upgrade-strategy eager
else
    # Any other OS
    pip install -e . --upgrade --no-cache-dir --progress-bar off --upgrade-strategy eager
fi
