# @package _group_
train_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/dev_10.tsv
val_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/dev_10.tsv
test_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/dev_10.tsv
columns:
- text
- label
batch_size: 4
is_shuffle: False
transform:
  label_names:
    - 0
    - 1
  vocab_path: manifold://nlp_technologies/tree/pytext/public/vocabs/vocab_dummy.txt
