# @package _group_
train_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/train.tsv
val_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/dev.tsv
test_path: manifold://nlp_technologies/tree/pytext/public/datasets/glue_sst2/dev.tsv
columns:
- text
- label
batch_size: 32
is_shuffle: False
transform:
  label_names:
    - 0
    - 1
  vocab_path: manifold://nlp_technologies/tree/xlm/models/xlm_r/vocab
